apiVersion: v1
kind: Secret
metadata:
  name: messager-db-secret

type: Opaque

stringData:
  USER_DB_DSN: "host=postgres-dev user=admin password=admin42 dbname=messager_users sslmode=disable"
  MSG_DB_DSN: "host=postgres-dev user=admin password=admin42 dbname=messager_messages sslmode=disable"
