apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv-messager-uploads
  namespace: messager

spec:
  storageClassName: standard
  capacity:
    storage: 10Gi

  accessModes:
    - ReadWriteMany

  persistentVolumeReclaimPolicy: Retain

  mountOptions:
    - allow-delete
    - url=http://localhost:9000
    - use_path_request_style

  csi:
    driver: ru.yandex.s3.csi

    volumeHandle: messager-uploads-volume

    nodePublishSecretRef:
      name: csi-s3-secret
      namespace: messager

    volumeAttributes:
      bucketName: messager-uploads
      mounter: rclone

