apiVersion: v1
kind: Secret
metadata:
  name: messager-db-secret
  namespace: messager

type: Opaque

stringData:
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "admin42"

  USER_DB_DSN: "host=postgres user=admin password=admin42 dbname=messager_users sslmode=disable"

  MSG_DB_DSN: "host=postgres user=admin password=admin42 dbname=messager_messages sslmode=disable"
